services:
  app:
    build: .
    expose:
      - "80"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - gov-ai-backend-net
      - easypanel

networks:
  gov-ai-backend-net:
    name: gov-ai-backend-net
    ipam:
      config:
        - subnet: 10.200.175.0/24
  easypanel:
    external: true
