export enum SupportLevel {
  FIRME = 'FIRME',
  SIMPATIZANTE = 'SIMPATIZANTE',
  INDEFINIDO = 'INDEFINIDO',
  OPOSICAO = 'OPOSICAO',
}

export enum ConfidenceLevel {
  ALTO = 'ALTO',
  NEUTRO = 'NEUTRO',
  BAIXO = 'BAIXO',
}

export enum HelpCategory {
  SAUDE = 'SAUDE',
  EDUCACAO = 'EDUCACAO',
  ASSISTENCIA_SOCIAL = 'ASSISTENCIA_SOCIAL',
  INFRAESTRUTURA = 'INFRAESTRUTURA',
  EMPREGO = 'EMPREGO',
  DOCUMENTACAO = 'DOCUMENTACAO',
  OUTROS = 'OUTROS',
}

export enum HelpStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum TaskStatus {
  PENDENTE = 'PENDENTE',
  EM_ANDAMENTO = 'EM_ANDAMENTO',
  CONCLUIDA = 'CONCLUIDA',
  ATRASADA = 'ATRASADA',
}

export enum TaskPriority {
  BAIXA = 'BAIXA',
  MEDIA = 'MEDIA',
  ALTA = 'ALTA',
  URGENTE = 'URGENTE',
}

export enum AppointmentType {
  COMPROMISSO = 'COMPROMISSO',
  ACAO = 'ACAO',
  REUNIAO = 'REUNIAO',
  VISITA = 'VISITA',
  LIGACAO = 'LIGACAO',
  OUTRO = 'OUTRO',
}

export enum AppointmentStatus {
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  IN_PROGRESS = 'IN_PROGRESS',
}

export enum ProjectStatus {
  EM_ELABORACAO = 'EM_ELABORACAO',
  PROTOCOLADO = 'PROTOCOLADO',
  EM_TRAMITACAO = 'EM_TRAMITACAO',
  APROVADO = 'APROVADO',
  REJEITADO = 'REJEITADO',
  ARQUIVADO = 'ARQUIVADO',
}

export enum BillType {
  PL = 'PL',
  PEC = 'PEC',
  PLP = 'PLP',
  PDL = 'PDL',
  MPV = 'MPV',
  REQ = 'REQ',
  INC = 'INC',
}

export enum BillStatus {
  EM_TRAMITACAO = 'EM_TRAMITACAO',
  APROVADO = 'APROVADO',
  REJEITADO = 'REJEITADO',
  ARQUIVADO = 'ARQUIVADO',
  RETIRADO = 'RETIRADO',
}

export enum BillAuthorship {
  PROPRIO = 'PROPRIO',
  COAUTORIA = 'COAUTORIA',
  ACOMPANHAMENTO = 'ACOMPANHAMENTO',
}

export enum AmendmentStatus {
  APROVADA = 'APROVADA',
  EM_EXECUCAO = 'EM_EXECUCAO',
  EXECUTADA = 'EXECUTADA',
  CANCELADA = 'CANCELADA',
}

export enum VoteChoice {
  FAVORAVEL = 'FAVORAVEL',
  CONTRARIO = 'CONTRARIO',
  ABSTENCAO = 'ABSTENCAO',
  AUSENTE = 'AUSENTE',
  OBSTRUCAO = 'OBSTRUCAO',
}

export enum VoteResult {
  APROVADO = 'APROVADO',
  REJEITADO = 'REJEITADO',
  ADIADO = 'ADIADO',
}

export enum ContactRole {
  PREFEITO = 'PREFEITO',
  VEREADOR = 'VEREADOR',
  LIDERANCA_COMUNITARIA = 'LIDERANCA_COMUNITARIA',
  SECRETARIO = 'SECRETARIO',
  DEPUTADO_ESTADUAL = 'DEPUTADO_ESTADUAL',
  DEPUTADO_FEDERAL = 'DEPUTADO_FEDERAL',
  SENADOR = 'SENADOR',
  OUTRO = 'OUTRO',
}

export enum ContactRelationship {
  ALIADO = 'ALIADO',
  NEUTRO = 'NEUTRO',
  OPOSICAO = 'OPOSICAO',
}

export enum TransactionType {
  DESPESA = 'DESPESA',
  RECEITA = 'RECEITA',
}

export enum TransactionStatus {
  PENDENTE = 'PENDENTE',
  PAGA = 'PAGA',
  CANCELADA = 'CANCELADA',
}

export enum ExpenseCategory {
  PASSAGENS = 'PASSAGENS',
  TELEFONIA = 'TELEFONIA',
  POSTAIS = 'POSTAIS',
  MANUTENCAO = 'MANUTENCAO',
  CONSULTORIA = 'CONSULTORIA',
  DIVULGACAO = 'DIVULGACAO',
  COMBUSTIVEL = 'COMBUSTIVEL',
  HOSPEDAGEM = 'HOSPEDAGEM',
  ALIMENTACAO = 'ALIMENTACAO',
  VEICULOS = 'VEICULOS',
  SEGURANCA = 'SEGURANCA',
  OUTROS = 'OUTROS',
}

export enum RequestType {
  OFICIO = 'OFICIO',
  INDICACAO = 'INDICACAO',
  REQUERIMENTO = 'REQUERIMENTO',
}

export enum RequestStatus {
  ENVIADO = 'ENVIADO',
  EM_ANALISE = 'EM_ANALISE',
  RESPONDIDO = 'RESPONDIDO',
  ATENDIDO = 'ATENDIDO',
  NEGADO = 'NEGADO',
}
