export enum PoliticalProfile {
  VEREADOR = 'VEREADOR',
  PREFEITO = 'PREFEITO',
  VICE_PREFEITO = 'VICE_PREFEITO',
  DEPUTADO_ESTADUAL = 'DEPUTADO_ESTADUAL',
  DEPUTADO_FEDERAL = 'DEPUTADO_FEDERAL',
  SENADOR = 'SENADOR',
  GOVERNADOR = 'GOVERNADOR',
  VICE_GOVERNADOR = 'VICE_GOVERNADOR',
  SECRETARIO = 'SECRETARIO',
}

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  TENANT_ADMIN = 'TENANT_ADMIN',
  MANAGER = 'MANAGER',
  ADVISOR = 'ADVISOR',
  LEADER = 'LEADER',
  VIEWER = 'VIEWER',
  ATTENDANT = 'ATTENDANT',
  RECEPTIONIST = 'RECEPTIONIST',
}

export enum ModuleCategory {
  CORE = 'CORE',
  GESTAO = 'GESTAO',
  ELEITORAL = 'ELEITORAL',
  LEGISLATIVO = 'LEGISLATIVO',
  COMUNICACAO = 'COMUNICACAO',
  FINANCEIRO = 'FINANCEIRO',
  GABINETE = 'GABINETE',
  POLITICO = 'POLITICO',
  INTELIGENCIA = 'INTELIGENCIA',
}

export enum BillingCycle {
  MONTHLY = 'MONTHLY',
  YEARLY = 'YEARLY',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  EXPORT = 'EXPORT',
}

export enum LeadFunnelStatus {
  NOVO = 'NOVO',
  INTERESSADO = 'INTERESSADO',
  NEGOCIANDO = 'NEGOCIANDO',
  FECHADO = 'FECHADO',
  PERDIDO = 'PERDIDO',
}

export enum CheckoutStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum MpResourceType {
  PREFERENCE = 'PREFERENCE',
  PREAPPROVAL = 'PREAPPROVAL',
}

export enum PaymentType {
  ONE_TIME = 'ONE_TIME',
  RECURRING = 'RECURRING',
}

export enum CheckoutSource {
  LANDING_PAGE = 'landing-page',
  ADMIN = 'admin',
}
